/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clase03.Agenda.Interfaces;

import Clase03.Agenda.Clases.Amigo;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author kaimo
 */
public class Agenda_Add extends javax.swing.JFrame {
    SessionNow now;
    String amigo_de;
    String user_now;
    
    public Agenda_Add() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Agenda_Add(SessionNow session){
        initComponents();
        setLocationRelativeTo(null);
        amigo_de = session.getEmail_now();
        user_now = session.getUser_now();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBL_back = new javax.swing.JLabel();
        LBL_exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBL_name = new javax.swing.JLabel();
        TXT_name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LBL_surname = new javax.swing.JLabel();
        TXT_surname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LBL_phone = new javax.swing.JLabel();
        TXT_phone = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        LBL_email = new javax.swing.JLabel();
        TXT_email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        YearC_year = new com.toedter.calendar.JYearChooser();
        MonthC_month = new com.toedter.calendar.JMonthChooser();
        TXT_day = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        LBL_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Back_15px.png"))); // NOI18N
        LBL_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL_backMouseClicked(evt);
            }
        });

        LBL_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Delete_20px.png"))); // NOI18N
        LBL_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL_exit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_exit)
                    .addComponent(LBL_back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        LBL_name.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LBL_name.setForeground(new java.awt.Color(204, 204, 204));
        LBL_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Add User Male_15px.png"))); // NOI18N
        LBL_name.setText("Name:");

        TXT_name.setBackground(new java.awt.Color(36, 47, 65));
        TXT_name.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TXT_name.setForeground(new java.awt.Color(255, 255, 255));
        TXT_name.setBorder(null);

        LBL_surname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LBL_surname.setForeground(new java.awt.Color(204, 204, 204));
        LBL_surname.setText("Surname:");

        TXT_surname.setBackground(new java.awt.Color(36, 47, 65));
        TXT_surname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TXT_surname.setForeground(new java.awt.Color(255, 255, 255));
        TXT_surname.setBorder(null);

        LBL_phone.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LBL_phone.setForeground(new java.awt.Color(204, 204, 204));
        LBL_phone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/iPhone_15px.png"))); // NOI18N
        LBL_phone.setText("Phone:");

        TXT_phone.setBackground(new java.awt.Color(36, 47, 65));
        TXT_phone.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TXT_phone.setForeground(new java.awt.Color(255, 255, 255));
        TXT_phone.setBorder(null);

        LBL_email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LBL_email.setForeground(new java.awt.Color(204, 204, 204));
        LBL_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Post_15px.png"))); // NOI18N
        LBL_email.setText("Email:");

        TXT_email.setBackground(new java.awt.Color(36, 47, 65));
        TXT_email.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TXT_email.setForeground(new java.awt.Color(255, 255, 255));
        TXT_email.setBorder(null);

        TXT_day.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_dayActionPerformed(evt);
            }
        });
        TXT_day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_dayKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Birthday Cake_15px.png"))); // NOI18N
        jLabel1.setText("Birth:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Year");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Day");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Month");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clase03/Agenda/Images/Add User Male_15px_blue.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LBL_surname)
                                .addComponent(LBL_phone)
                                .addComponent(LBL_name))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator1)
                                .addComponent(TXT_name)
                                .addComponent(TXT_surname)
                                .addComponent(TXT_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LBL_email)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4)
                                .addComponent(TXT_email, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(YearC_year, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(MonthC_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(TXT_day)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_name)
                    .addComponent(TXT_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_surname)
                    .addComponent(TXT_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_phone)
                    .addComponent(TXT_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_email)
                    .addComponent(TXT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(YearC_year, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(MonthC_month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXT_day)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(jToggleButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBL_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LBL_exitMouseClicked

    private void LBL_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_backMouseClicked
        this.setVisible(false);
        now.setEmail_now(amigo_de);
        now.setUser_now(user_now);
        Agenda go = new Agenda(now);
        go.setVisible(true);
    }//GEN-LAST:event_LBL_backMouseClicked

    private void TXT_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_dayActionPerformed

    private void TXT_dayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_dayKeyTyped
        int limit_days = 2;
        if ( (TXT_day.getText().length()== limit_days) ) {
            if ((Integer.parseInt(TXT_day.getText())<=31 &&
                Integer.parseInt(TXT_day.getText())>=1)) {
            evt.consume();
            TXT_day.transferFocus();
        }
        }
    }//GEN-LAST:event_TXT_dayKeyTyped

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Amigo amigo = new Amigo();       
        Calendar month = new GregorianCalendar();
        int monthP = month.get(Calendar.MONTH);
        String format_date = "", mes, anio, dia;
        
        amigo.setName(TXT_name.getText().toUpperCase().trim());
        amigo.setSurname(TXT_surname.getText().toUpperCase().trim());
        amigo.setEmail(TXT_email.getText().trim());
        amigo.setPhone(TXT_phone.getText().trim());
        
        anio = Integer.toString(YearC_year.getYear());
        mes = Integer.toString(MonthC_month.getMonth()+1);
        dia = TXT_day.getText();
        if (Integer.parseInt(mes)<10)
            format_date = anio+"-0"+mes+"-"+dia;
        else
            format_date = anio+"-"+mes+"-"+dia;
        
        amigo.setBirthday(format_date);
        amigo.setEmail_amigo(amigo_de);
        
        System.out.println("|----- AMIGO A AGREGAR ------|");
        System.out.println("Name:\t\t"+amigo.getName());
        System.out.println("Surname:\t"+amigo.getSurname());
        System.out.println("Phone:\t\t"+amigo.getPhone());
        System.out.println("Email:\t\t"+amigo.getEmail());
        System.out.println("Birthday:\t"+amigo.getBirthday());
        System.out.println("Friend of:\t\t"+amigo.getEmail_amigo());
        System.out.println("|----------------------------|");
        
        matchServer(amigo);
        this.setVisible(false);
        Agenda go = new Agenda();
        go.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_back;
    private javax.swing.JLabel LBL_email;
    private javax.swing.JLabel LBL_exit;
    private javax.swing.JLabel LBL_name;
    private javax.swing.JLabel LBL_phone;
    private javax.swing.JLabel LBL_surname;
    private com.toedter.calendar.JMonthChooser MonthC_month;
    private javax.swing.JTextField TXT_day;
    private javax.swing.JTextField TXT_email;
    private javax.swing.JTextField TXT_name;
    private javax.swing.JTextField TXT_phone;
    private javax.swing.JTextField TXT_surname;
    private com.toedter.calendar.JYearChooser YearC_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    public void matchServer(Amigo amigo){
        try{
            System.out.println("matchSever");
            int puerto = 8888;
            String dst = "127.0.0.1";
            Socket cliente = new Socket(dst,puerto);
            System.out.println("Conexion establecida...\nProduciendo objeto");
            System.out.println("|------ AMIGO A ENVIAR -------|");
            System.out.println("Name:\tt"+amigo.getName());
            System.out.println("Surname:\t\t"+amigo.getSurname());
            System.out.println("Phone:\t\t"+amigo.getPhone());
            System.out.println("Email:\t\t"+amigo.getEmail());
            System.out.println("Birthday:\t\t"+amigo.getBirthday());
            System.out.println("Firend of:\t"+amigo.getEmail_amigo());
            System.out.println("|-----------------------------|");
            
            ObjectOutputStream oos = new ObjectOutputStream(cliente.getOutputStream());
            ObjectInputStream ois = new ObjectInputStream(cliente.getInputStream());

            oos.writeObject(amigo);
            oos.flush();
            
            System.out.println(">-- Objeto enviado --<");
            System.out.println(">-- Esperando respuesta --<");
            System.out.println(">--  ...... --<");
            
            ois.close();
            oos.close();
            cliente.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
