create database AGENDA_REDES2;

CREATE TABLE PERSONS (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
PHONE VARCHAR(30) NOT NULL,
BIRTHDAY DATE NOT NULL,
EMAIL VARCHAR(50)
);